'use client';
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/navBar/page';
import { usePathname } from 'next/navigation';
import Admin from './components/administration/panel/page'
import { useEffect, useState } from 'react';

const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const links = [{
  label:"Home",
  route:"/"
},
{
  label:"UserLogin",
  route:"/UserLogin"
}]


export default function RootLayout(
  {
  children,
}: {
  children: React.ReactNode
}) 
{
  const [admin, setAdmin] = useState(false)
  const pathname = usePathname()
  const pathAdmin = pathname.includes('administration')
  useEffect(() => {
    setAdmin(pathAdmin)
    console.log(admin);
    

    
    
  }, [pathname]);
  
  return (
    <html lang="en">
      <body  className={inter.className}>
        <header>
          <Navbar/>
        </header>
        <main className={admin ? 'admin_main': inter.className}>
        {admin && <Admin/>}
          
          <section>
            {children}
          </section>
        </main>
        </body>
    </html>
  )
}
